### ISSUE TITLE
UI - Segmentation

### ISSUE THREAD

**Issue by happiness330** [segsalerty2013/karakata-online#12]
- Set up a clickable segmentation button
- Phone numbers selection page
- Set up a messaging template
- Set up a send message button.
![Segmentation (1)](https://user-images.githubusercontent.com/97968167/151344573-f2f17c90-4b07-4bef-aaac-e62932f4a291.png)

**Comment by boyeoffice** [comment]
I want to work on this

**Comment by happiness330** [comment]
Sure thing @boyeoffice 
kindly indicate the start date
