### ISSUE TITLE
UI - Dashboard Header & SideBar

### ISSUE THREAD

**Issue by odetolakehinde** [segsalerty2013/karakata-online#13]
Design only the Dashboard and the Sidebar
![Frame 270](https://user-images.githubusercontent.com/26208992/151331998-b04c5b3b-8986-4b51-a5e3-192fb252c155.png)
<img width="868" alt="Screenshot 2022-01-27 at 10 35 46" src="https://user-images.githubusercontent.com/26208992/151332076-81f31436-a0dd-4d2d-8a10-01329f185847.png">

**Comment by Afunnilo** [comment]
i want to work on this

**Comment by odetolakehinde** [comment]
> i want to work on this

Go for it. I just assigned it to you. Remember to use components and name them `TheHeader` and `TheSideBar` respectively.

**Comment by boyeoffice** [comment]
I want to work on this
