### ISSUE TITLE
UI - Create Account Page

### ISSUE THREAD

**Issue by happiness330** [segsalerty2013/karakata-online#5]
SLIDE 1
- Business Name button: give access to input this
- Business Address: give access to input this
- Business Telephone: give access to input this
- Business State: give access to input this
_ Business country: give access to input this
- The business year of establishment: give access to input this
- The business month of establishment: give access to input this
- Business Kind: give access to input this

SLIDE 2
- Business sales channel: give access to input this
- Business average sale per year: give access to input this
- Business contact designation: give access to input this
- Contact designation: give access to input this
- Contact phone number: give access to input this
-Business average existing customer: give access to input this
- Business employee count: give access to input this
- Contact name: give access to input this
- Make the previous button accessible: give access to input this
- Hyperlink the Setup button: give access to input this
![Sign In](https://user-images.githubusercontent.com/97968167/151342626-842ee197-ef15-4378-a7f6-41491bde5706.png)
![Sign In (1)](https://user-images.githubusercontent.com/97968167/151342872-2f70b449-2e9a-409b-a462-ef4f0908e425.png)

**Comment by boyeoffice** [comment]
I will work on this one. What node version used to setup this codebase?
