### ISSUE TITLE
UI - Sign In Page

### ISSUE THREAD

**Issue by happiness330** [segsalerty2013/karakata-online#6]
- Email Address: Make it more responsive
- Password: Make it more responsive
- Remember me: Make it more responsive
- Forgot password: hyperlink 
- Sign In:  Make it more responsive

![Dashboard (1)](https://user-images.githubusercontent.com/97968167/151342184-40913c47-d01e-4bc3-9f28-f2b1c916a5ad.png)

**Comment by blade-01** [comment]
I want to work on this @happiness330

**Comment by happiness330** [comment]
Alright @blade-01

**Comment by happiness330** [comment]
please indicate here, the start date @blade-01

**Comment by blade-01** [comment]
I'd be starting tomorrow, February 2nd
